### ISSUE TITLE
When there is a failure at parsing the input file, we should at least tell which line the error was

### ISSUE THREAD

**Issue by bentiss** [whot/uji#1]
For example, `fail_parse.yaml`:
```yaml
generic_laptop_keyboard:
  type: actor
  name: AT Translated Keyboard
  description: the PS/2 thing with keys as found in laptops
  tags:
    type: keyboard

generic_usb_keyboard:
  extends: obviously wrong

test_keyboard:
  type: test
  filter:
    type: keyboard
  tests:
    - make sure we can type keys
```

Leads to:
```bash
> ./uji/uji.py new fail_parse.yaml
CRITICAL: Failed to parse YAML file: Invalid section for "extends: {referenced}"
```
