### ISSUE TITLE
Allow for multiple generic groups

### ISSUE THREAD

**Issue by whot** [whot/uji#16]
Tests without filters are currently merged into one "Generic" group. This isn't always useful, sometimes keeping the grouping from the templates is more useful.

This can be worked around by having a dummy generic actor with a filter (see below), but maybe there's an easier way?

```yaml
# Dummy actor for a generic task that should stay in its own group
dummy:
   name: Generic tasks
   type: actor
   tags:
      something: dummy

# Test with a dummy filter to keep it in its own markdown section
mytest:
   type: test
   filter:
     something: [dummy]
   test:
    - this should be easier
```

*maybe* something like a `merge: false` tag to prevent it from being added to the generic list?
