### ISSUE TITLE
include: statements should take a files list

### ISSUE THREAD

**Issue by whot** [whot/uji#22]
We support `include: filename` anywhere but using multiple includes fails Yaml parsers, e.g. this yaml is invalid:
```yaml

include: foo
include: bar  # duplicate include key
...
```
technically valid I think but some parsers complain about it. Better for us to support:
```
include:
   files: [ foo, bar]
```
the nesting in `files` means we can add other keys to it later if we need to
